apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-calculator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-calculator
  template:
    metadata:
      labels:
        app: flask-calculator
    spec:
      containers:
        - name: flask-app
          image: mshmsudd/flask-app
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-calculator
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: flask-calculator